export const ADD_USER = "ADD_USER";
export const USER_ADDED = "USER_ADDED";
export const LOGIN = 'LOGIN';
export const RESPONSE_ACTION='RESPONSE_ACTION'
export const CHANGE_ERROR_VALUE='CHANGE_ERROR_VALUE'
export const ADD_POLL='ADD_POLL'
export const LIST_USERS='LIST_USERS'
export const LIST_USERS_SUCESS='LIST_USERS_SUCESS'